FROM hyperionorg/hyperion-ci:ubuntu1604

# Set the working directory to /build
WORKDIR /build

# Copy the current directory contents into the container at /build
COPY . /build

# compile
RUN  mkdir build && cd build \
      && cmake -DCMAKE_BUILD_TYPE=Release .. \
      && make -j $(nproc) package
